# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: badgerItem.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'badgerItem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62\x61\x64gerItem.proto\"?\n\x04Item\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05ver64\x18\x03 \x01(\x04\x12\r\n\x05sum64\x18\x04 \x01(\x04\"e\n\tItemReply\x12\x0f\n\x07\x65rrcode\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\x0c\x12\x0b\n\x03key\x18\x03 \x01(\x0c\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\r\n\x05ver64\x18\x05 \x01(\x04\x12\r\n\x05sum64\x18\x06 \x01(\x04\"-\n\nListFilter\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x0f\n\x07pagenum\x18\x02 \x01(\x05\"\x1f\n\x0fListFilterReply\x12\x0c\n\x04keys\x18\x01 \x03(\t2\xc5\x01\n\x06\x42\x61\x64ger\x12\x1a\n\x03Get\x12\x05.Item\x1a\n.ItemReply\"\x00\x12\x1a\n\x03Set\x12\x05.Item\x1a\n.ItemReply\"\x00\x12\x1d\n\x06\x44\x65lete\x12\x05.Item\x1a\n.ItemReply\"\x00\x12\x1d\n\x06\x45xists\x12\x05.Item\x1a\n.ItemReply\"\x00\x12\x1c\n\x05\x41\x64min\x12\x05.Item\x1a\n.ItemReply\"\x00\x12\'\n\x04List\x12\x0b.ListFilter\x1a\x10.ListFilterReply\"\x00\x42 Z\x1egithub.com/harryzhu/zstdfs/pbsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'badgerItem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/harryzhu/zstdfs/pbs'
  _globals['_ITEM']._serialized_start=20
  _globals['_ITEM']._serialized_end=83
  _globals['_ITEMREPLY']._serialized_start=85
  _globals['_ITEMREPLY']._serialized_end=186
  _globals['_LISTFILTER']._serialized_start=188
  _globals['_LISTFILTER']._serialized_end=233
  _globals['_LISTFILTERREPLY']._serialized_start=235
  _globals['_LISTFILTERREPLY']._serialized_end=266
  _globals['_BADGER']._serialized_start=269
  _globals['_BADGER']._serialized_end=466
# @@protoc_insertion_point(module_scope)
