<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: badgerItem.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The request message containing the user's name.
 *
 * Generated from protobuf message <code>Item</code>
 */
class Item extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     */
    protected $data = '';
    /**
     * Generated from protobuf field <code>uint64 ver64 = 3;</code>
     */
    protected $ver64 = 0;
    /**
     * Generated from protobuf field <code>uint64 sum64 = 4;</code>
     */
    protected $sum64 = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type string $data
     *     @type int|string $ver64
     *     @type int|string $sum64
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BadgerItem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>bytes data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 ver64 = 3;</code>
     * @return int|string
     */
    public function getVer64()
    {
        return $this->ver64;
    }

    /**
     * Generated from protobuf field <code>uint64 ver64 = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVer64($var)
    {
        GPBUtil::checkUint64($var);
        $this->ver64 = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 sum64 = 4;</code>
     * @return int|string
     */
    public function getSum64()
    {
        return $this->sum64;
    }

    /**
     * Generated from protobuf field <code>uint64 sum64 = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSum64($var)
    {
        GPBUtil::checkUint64($var);
        $this->sum64 = $var;

        return $this;
    }

}

