<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: badgerItem.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ListFilter</code>
 */
class ListFilter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string prefix = 1;</code>
     */
    protected $prefix = '';
    /**
     * Generated from protobuf field <code>int32 pagenum = 2;</code>
     */
    protected $pagenum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $prefix
     *     @type int $pagenum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\BadgerItem::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string prefix = 1;</code>
     * @return string
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Generated from protobuf field <code>string prefix = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPrefix($var)
    {
        GPBUtil::checkString($var, True);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 pagenum = 2;</code>
     * @return int
     */
    public function getPagenum()
    {
        return $this->pagenum;
    }

    /**
     * Generated from protobuf field <code>int32 pagenum = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPagenum($var)
    {
        GPBUtil::checkInt32($var);
        $this->pagenum = $var;

        return $this;
    }

}

